### ISSUE TITLE
Error at offset 0 of 5 when trying to unserialize

### ISSUE THREAD

**Issue by crewxp** [bliswebagency/Download-File#2]
I'm installing this plugin for the first time. In my template (site/support) I placed 

{exp:download_file:serve restricted="internaldomain.com"}

and in my published entry, I created a entry called Aclaro. In it, I placed. 
"<a href="{exp:download_file:link file='/support/aclaro/accaro_manuals/AclaroQuickReference.pdf' template='/site/support'}">Aclaro QuickReference</a>"

But I get a PHP Error at the top and the page doesn't render. The same goes for all of my support pages, not just the one I used the :link line of code in.

If I use:
"{exp:download_file:serve}"

instead, it gives me the same php error but it loads the rest of the page. my generated download link is:
http://www4.internaldomain.com/system//site/supportczo1ODoiL3N1cHBvcnQvYWNjbGFyby9hY2NsYXJvX21hbnVhbHMvQWNjbGFyb1F1aWNrUmVmZXJlbmNlLnBkZiI7

The full error is:
"A PHP Error was encountered

Severity: Notice

Message: unserialize() [function.unserialize]: Error at offset 0 of 5 bytes

Filename: download_file/pi.download_file.php

Line Number: 62"

---

Any guesses as to what could be wrong? I'm running EE2.2.3 and have been at it for hours.

**Comment by bliswebagency** [comment]
Hi Crewxp,

Just to clarify; did you mean you're using EE 2.1.3? It shouldn't matter but I must admit we've been a little slow adopting the new version 2.2.1 whilst we wait for things to even out.

It could be that the PHP error is occurring because there's a path error. Is the plugin actually working despite the PHP Notice? If so and you're after a fast fix, you can just add:

```
error_reporting(0);
```

To the top of /system/expressionengine/third_party/download_file/pi.download_file.php underneath the line:

```
class Download_file {
```

Alternatively you can download a version I prepared earlier here: http://cl.ly/070U0S0I3l0q180U3E2j

If it's not working and/or you have a little time to help me make the plugin a little more robust, then I'd love to know a couple more things like:
1. What version of PHP are you using and
2. Are you on a Apache server

Look forward to hearing back from you.

**Comment by bliswebagency** [comment]
Sorry didn't mean to close it - not used to this GitHub support system...!

**Comment by bliswebagency** [comment]
Oh, one more thing: would you mind changing

```
{exp:download_file:link file="/whatever/support.pdf" template="/site/support"}
```

to

```
{exp:download_file:link file="/whatever/support.pdf" template="/site/support/"}
```

The trailing slash is important.

**Comment by crewxp** [comment]
Thanks for the reply. I'm glad you guys still provide a little support. I
don't mind at all helping out, especially if it means the plugin gets full
compatibility for everyone.

I added the trailing slash and still have the same problem. Do you think its
a apache/php version issue? When running the file at the link given, I get:

_Parse error_: syntax error, unexpected T_STRING, expecting T_FUNCTION in *
/var/www/www4/system/expressionengine/third_party/download_file/pi.download_file.php
- on line *39

*Apache VersionApache/2.0.63 (CentOS)Apache API Version20020903PHP Version
5.1.6

**Comment by crewxp** [comment]
Update.

I got it working!!

The error_reporting(0); I had to place at the very top of my download_file.php file, right under where the php tag starts.

Then the template needs to be changed from /site/support/ (the template location)

to /index.php/support/  

I guess index.php is how the new EE renders pages? Took a while, but I'm glad its fixed now :)

Thank you for the bump in direction on where to go. Glad to say its fully working now.

**Comment by bliswebagency** [comment]
Ah, indeed I didn't think about that you may not have removed index.php from your URLs. You can use your .htaccess file to remove this from your paths which makes little difference to how the site functions but looks a little nicer. If you're keen to do this, EllisLab have published a guide here: http://goo.gl/hOY9L

Thanks for letting us know everything is now under control. Please feel free to get back in touch again if you have any more queries.
