### ISSUE TITLE
Adding restricted to serve tag in template stops page views

### ISSUE THREAD

**Issue by crewxp** [bliswebagency/Download-File#3]
Hi, Sorry to create another ticket, but seems I have another problem with EE2.1 and the download-file plugin.

It works fine if I use {exp:download_file:serve} in the template. My :link tags work fine and download. But it seems people can just copy paste that link into a browser and download it using that. (I think this is called hotlinking?)

I wanted to prevent that. So I read in the guide to add restricted to my template. so I tried.

{exp:download_file:serve restricted="internalsite.com"} and {exp:download_file:serve restricted="internalsite.com" errors="off"} are both tags I have tried.

Whenever I use those though, my pages are blank. I'm thinking there is an error that comes up and is preventing it from showing. When I don't use restricted, it works fine.

**Comment by bliswebagency** [comment]
Hi Crewxp,

Indeed you're correct, you do need to add the "restricted" parameter to prevent hotlinking, otherwise the plugin just serves the file to anyone. In terms of the tag you need to use, it does need to be the first one you tried e.g. 

```
{exp:download_file:serve restricted="internalsite.com"}
```

If you then try to access this page from any other location, it will redirect the user to your homepage.

If you are seeing a white page however, it can be a sign of memory issue (ie. lack of memory). To rule this out, try put some extra "test" text on the template which is serving the file. Add it below the plugin, something like this:

```
{exp:download_file:serve restricted="internalsite.com"}

Downloading file...
```

If you can see the words "downloading file", it rules out the memory issue and comes back to the plugin again.

You may also want to check that Safe Mode is OFF in your PHP settings.
